# spark core config

spark.sql.catalogImplementation hive

spark.sql.warehouse.dir s3a://university-analytics/warehouse/

spark.serializer org.apache.spark.serializer.KryoSerializer

spark.sql.shuffle.partitions 4

spark.sql.session.timeZone UTC

# S3A (OK ICI car Spark only)
spark.hadoop.fs.s3a.endpoint http://minio:9000
spark.hadoop.fs.s3a.path.style.access true
spark.hadoop.fs.s3a.connection.ssl.enabled false
spark.hadoop.fs.s3a.impl org.apache.hadoop.fs.s3a.S3AFileSystem

spark.hadoop.fs.s3a.access.key ${MINIO_ROOT_USER}
spark.hadoop.fs.s3a.secret.key ${MINIO_ROOT_PASSWORD}