# spark core config

spark.sql.catalogImplementation hive

spark.serializer org.apache.spark.serializer.KryoSerializer



# MinIO - Warhouse

spark.sql.warehouse.dir s3a://university-analytics/warehouse/



# performance et ressources utilisé en dev

spark.driver.memory 2g

spark.executor.memory 2g

spark.sql.shuffle.partitions 4

spark.sql.session.timeZone UTC



# Hudi support (IMPORTANT)

spark.sql.extensions org.apache.spark.sql.hudi.HoodieSparkSessionExtension



# paquet/hudi comptabilité

spark.sql.parquet.compression.codec snappy

spark.sql.sources.partitionOverwriteMode dynamic



# MinIO S3A config

spark.hadoop.fs.s3a.endpoint http://minio:9000

spark.hadoop.fs.s3a.path.style.access true

spark.hadoop.fs.s3a.connection.ssl.enabled false

spark.hadoop.fs.s3a.impl org.apache.hadoop.fs.s3a.S3AFileSystem



# IMPORTANT:

# Les credentials NE DOIVENT PAS être fixés ici

# Ils seront injectés via docker-compose / env / spark-submit
